### ISSUE TITLE
Widgets/Skins are with a white background.

### ISSUE THREAD

**Issue by NNickey** [MinhThienDX/win10widgets#22]
![image](https://user-images.githubusercontent.com/3466265/79539976-98541480-8044-11ea-91ab-2a0f75f11070.png)

**Comment by Kablion** [comment]
@NNickey Can you give us a little more information? Did you change anything? Which Theme do you use? (rightclick on a widget) Is there any warning or error in the log? (Rainmeter Manage Window on the bottom is a button for logs)

**Comment by NNickey** [comment]
Nope, the moment I installed these custom widgets that included the GPU option, all the widget backgrounds were white. I'll get images of all the data I can find.

**Comment by Vox-Ludus** [comment]
I experienced the same issue using 4.3.1 r3321.  Installing 4.4 r3349 resolved it. I did check the log on 4.3.1 (sorry, didn't save it), and there was a repeating error. "unable to read file SKIN/LOCATION/HERE/.png" It did end just like that, just "/.png" with no file name.

**Comment by pdbenbow** [comment]
Experienced the same issue with everything having a white background while using Rainmeter 4.0. All of my widgets were set to dark theme with 20% transparency, but backgrounds were still white and text was unreadable.

Fixed the issue by upgrading Rainmeter to 4.4 r3349 (https://builds.rainmeter.net/).

**Comment by Kablion** [comment]
Sadly I'm not able to recreate this bug even though I'm on the same version with which you encountered this error.

![Win10WidgetsBugWhite](https://user-images.githubusercontent.com/19869870/80797656-b07a7680-8ba2-11ea-97fc-266183589955.png)

An idea to fix this for anyone having troubles with this and who doesn't want to upgrade to 4.4:
Create a .png file at the same location the error points you to. Just a small maybe even transparent picture. 

I've found no point in the code where such an error with a .png could come from. Especially since you were not using the weather widget, which would be the only error source I can imagine.

**Comment by MinhThienDX** [comment]
@NNickey Any news on this?
I think it is fixed by Rainmeter.
